import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import NavBar from '@/app/ui/navBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} text-black bg-white dark:text-white dark:bg-black`}>
        <ThemeProvider attribute="class" >
          <NavBar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
